#!/bin/bash
#
# MIT License
#
# Copyright (c) 2020 Matthieu Petiteau
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# This script fetchs the tube line statuses from the TFL API
# https://api.tfl.gov.uk and returns the results in terminal.

set -e

if ! command -v jq &>/dev/null; then
  printf "Error: You need to install jq to run this script
https://stedolan.github.io/jq/download/\n"
  exit 1
fi

LINE_SEARCH=$1
DELIMITER="¬"
RED="\033[38;5;161m"
GREEN="\033[38;5;082m"
YELLOW="\033[38;5;226m"
NONE="\033[0m"
URL="https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status"

curl -s $URL |
  jq --arg delim $DELIMITER -j '.[] |
    (.name) + $delim,
    (.lineStatuses[0] | (.statusSeverity),
    $delim + (.statusSeverityDescription),
    $delim + (.reason) + "\n")' |
  awk -F $DELIMITER -v delim=$DELIMITER -v r=$RED \
    -v y=$YELLOW -v g=$GREEN -v n=$NONE -v line=$LINE_SEARCH '{
      if ( $4 ) reason=$4;
      else reason="";
      if ( $2 == 10 ) color=g;
      else if ( $2 == 20 ) color=r;
      else if ( $2 >= 8 ) color=y;
      else color=r;
      if ( index(tolower($1), tolower(line)) )
        print color "●" n, $1 delim $3 delim reason;
    }' | column -t -s $DELIMITER
