#!/bin/bash
# File  : tubestatus.sh
# Author: Matthieu Petiteau <mpetiteau.pro@gmail.com>
# Date  : 25.09.2019

# This script fetch the tube line statuses from the TFL API
# https://api.tfl.gov.uk and returns the results in terminal.

if ! command -v jq &>/dev/null; then
  echo "You need to install jq to run this script."
  echo "https://github.com/stedolan/jq"
  echo
  case "$OSTYPE" in
  solaris*)
    echo "pkgutil -i jq"
    ;;
  darwin*)
    echo "brew install jq"
    ;;
  linux*)
    echo "Debian/Ubuntu  sudo apt-get install jq"
    echo "Fedora         sudo dnf install jq"
    echo "openSUSE       sudo zipper install jq"
    echo "Arch           sudo pacman -Sy jq"
    ;;
  bsd*)
    echo "pkg install jq"
    ;;
  msys*)
    echo "chocolatey install jq"
    ;;
  *)
    echo "https://stedolan.github.io/jq/download/"
    ;;
  esac
  exit 0
fi

url="https://api.tfl.gov.uk/line/mode/tube,overground,dlr,tflrail/status"

curl -s "$url" |
  jq -j '.[] |
  "line_name=" + (.name | @sh), (.lineStatuses[0] |
  " line_status=" + (.statusSeverityDescription | @sh),
  " delay_reason=" + (.reason | @sh),
  " severity=" + (.statusSeverity | @sh) + "\n")' |
  while IFS= read -r line; do
    eval "$line"
    if [ $severity -eq 8 ] || [ $severity -eq 9 ]; then
      printf "\033[1;33m ● \033[0m %-20s $line_status | $delay_reason\n" "$line_name"
    elif [ $severity -lt 8 ]; then
      printf "\033[0;31m ● \033[0m %-20s $line_status | $delay_reason\n" "$line_name"
    else
      printf "\033[0;32m ● \033[0m %-20s $line_status\n" "$line_name"
    fi
  done
